name: Copy Master to Backup

on:
  push:
    branches:
      - master

jobs:
  copy-to-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Checkout the branch you want to rebase
        run: git checkout origin/master-backup

      - name: Initiate the rebase
        run: git rebase origin/master

      - name: Continue the rebase
        run: git rebase --continue

      - name: Push the changes (optional)
        run: git push --force
