name: Copy Master to Backup

on:
  push:
    branches:
      - master

jobs:
  copy-to-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and checkout master-backup branch
        run: git checkout -b master-backup

      - name: Merge changes from master
        run: git merge origin/master

      - name: Pull changes from master-backup
        run: git pull origin master-backup

      - name: Push changes to master-backup branch
        run: git push origin master-backup
