name: Copy Master to Backup

on:
  push:
    branches:
      - master

jobs:
  copy-to-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch --all
  
      - name: Checkout the branch you want to rebase
        run: git checkout master-backup

      - name: Initiate the rebase
        run: git merge master

      - name: Resolve merge conflicts using 'theirs' strategy
        run: git checkout --theirs .

      - name: Push the changes (optional)
        run: git push --force
